demo/index.html, etools-app-selector.html
@marko911 I made some updates to this element to match Evrim's style guide
=> style guide updates

etools-app-selector.html
fixed issue with large app-selector button on chrome
CH #4867
=> Fix polymer2 button size 

bower.json, etools-app-selector.html
=> Fix Edge style issue

etools-app-selector.js
[ch11342] Console error on navigate to admin section
=> [ch11342] Console error on navigate to admin section

etools-app-selector.html
=> Adds conditional rendering of icons based on user permissions in poly1

etools-app-selector.html
=> Adds conditional rendering of icons based on user permissions

etools-app-selector.js
=> Adds conditional rendering of icons based on user permissions in poly3

etools-app-selector.js, package.json
[ch14186] Nothing Happens when you try to go back to FAM home page
=> [ch14186] Nothing Happens when you try to go back to home page

etools-app-selector.html
=> Updates power bi title and increases font size

etools-app-selector.js, package.json
Added css custom property for icon padding
=> Added css custom property for icon padding

etools-app-selector.js, package.json
=> Removes PSEA if user is a TPM

etools-app-selector.js, package.json
[ch17774] Fix app selector layout
=> [ch17774] Fix app selector layout

etools-app-selector.js, package-lock.json, package.json
[ch27671] [Added title property for component icon]
=> [ch27671] [Added title property for component icon]

.npmignore, package-lock.json, package.json
=> [ch27219]Add .npmignore & update outdated packages

package-lock.json, package.json, src/etools-app-selector.ts
[ch32646] App selector redirects to not-found before opening the selected app
=> [ch32646] App selector redirects to not-found before opening the selected app

package-lock.json, package.json, src/etools-app-selector.ts
[ch32793] Tab navigation: 13 tabs to skip the App selector and reach the Language dropdown
=> [ch32793] Tab navigation: 13 tabs to skip the App selector and reach the Language dropdown

package-lock.json, package.json, src/etools-app-selector.ts
=> [ch33128]Fix for rtl layout(4.0.8)

package-lock.json, package.json, src/etools-app-selector.ts
[ch33633] App selector not showing options, [Fixed js error before user data it's loaded]
=> [ch33633] App selector not showing options, [Fixed js error before user data it's loaded]

README.md, package-lock.json, package.json, src/etools-app-selector.ts
=> [ch33668]Fix lang init(4.0.10)

package-lock.json, package.json, src/etools-app-selector.ts
[ch34002] Inconsistency - tpm user can access AMP from Third Party Monitors list but AMP is not available in the app-selector
=> [ch34002] Inconsistency - tpm user can access AMP from Third Party Monitors list but AMP is not available in the app-selector
